/**
 * Catálogo de Costeras / Dependencias
 * Total: 130 registros
 * Generado automáticamente — no editar manualmente
 */

export const COSTERAS = [
  { id: 437, zona: "PZAP", nombre: "ELDO", etiqueta: "PZAP - ELDO" },
  { id: 418, zona: "PZAP", nombre: "IGUA", etiqueta: "PZAP - IGUA" },
  { id: 471, zona: "PZAP", nombre: "ITAE", etiqueta: "PZAP - ITAE" },
  { id: 446, zona: "PZAP", nombre: "ITUZ", etiqueta: "PZAP - ITUZ" },
  { id: 463, zona: "PZAP", nombre: "LIBE", etiqueta: "PZAP - LIBE" },
  { id: 470, zona: "PZAP", nombre: "POSA", etiqueta: "PZAP - POSA" },
  { id: 785, zona: "PZAP", nombre: "PULI", etiqueta: "PZAP - PULI" },
  { id: 925, zona: "PZAU", nombre: "ALPO", etiqueta: "PZAU - ALPO" },
  { id: 406, zona: "PZAU", nombre: "ALVE", etiqueta: "PZAU - ALVE" },
  { id: 438, zona: "PZAU", nombre: "LIBR", etiqueta: "PZAU - LIBR" },
  { id: 419, zona: "PZAU", nombre: "MCAS", etiqueta: "PZAU - MCAS" },
  { id: 945, zona: "PZAU", nombre: "PANA", etiqueta: "PZAU - PANA" },
  { id: 448, zona: "PZAU", nombre: "SJAV", etiqueta: "PZAU - SJAV" },
  { id: 926, zona: "PZAU", nombre: "SOBR", etiqueta: "PZAU - SOBR" },
  { id: 445, zona: "PZBP", nombre: "ASEC", etiqueta: "PZBP - ASEC" },
  { id: 614, zona: "PZBP", nombre: "ASEC (EMB-DEPORTIVAS)", etiqueta: "PZBP - ASEC (EMB-DEPORTIVAS)" },
  { id: 617, zona: "PZBP", nombre: "CORO (EMB-DEPORTIVAS)", etiqueta: "PZBP - CORO (EMB-DEPORTIVAS)" },
  { id: 408, zona: "PZBP", nombre: "DIAM", etiqueta: "PZBP - DIAM" },
  { id: 616, zona: "PZBP", nombre: "DIAM (EMB-DEPORTIVAS)", etiqueta: "PZBP - DIAM (EMB-DEPORTIVAS)" },
  { id: 420, zona: "PZBP", nombre: "LPAZ", etiqueta: "PZBP - LPAZ" },
  { id: 416, zona: "PZBP", nombre: "PARA", etiqueta: "PZBP - PARA" },
  { id: 442, zona: "PZBP", nombre: "RLLO", etiqueta: "PZBP - RLLO" },
  { id: 615, zona: "PZBP", nombre: "RLLO (EMB-DEPORTIVAS)", etiqueta: "PZBP - RLLO (EMB-DEPORTIVAS)" },
  { id: 422, zona: "PZBP", nombre: "ROSA", etiqueta: "PZBP - ROSA" },
  { id: 414, zona: "PZBP", nombre: "SAFE", etiqueta: "PZBP - SAFE" },
  { id: 618, zona: "PZBP", nombre: "SAFE (EMB-DEPORTIVAS)", etiqueta: "PZBP - SAFE (EMB-DEPORTIVAS)" },
  { id: 1025, zona: "PZBP", nombre: "SAFE (SAJV)", etiqueta: "PZBP - SAFE (SAJV)" },
  { id: 423, zona: "PZBP", nombre: "SLOR", etiqueta: "PZBP - SLOR" },
  { id: 619, zona: "PZBP", nombre: "SLOR (EMB-DEPORTIVAS)", etiqueta: "PZBP - SLOR (EMB-DEPORTIVAS)" },
  { id: 467, zona: "PZBP", nombre: "SNIC", etiqueta: "PZBP - SNIC" },
  { id: 621, zona: "PZBP", nombre: "SNIC (EMB-DEPORTIVAS)", etiqueta: "PZBP - SNIC (EMB-DEPORTIVAS)" },
  { id: 439, zona: "PZBP", nombre: "VCON", etiqueta: "PZBP - VCON" },
  { id: 620, zona: "PZBP", nombre: "VCON (EMB-DEPORTIVAS)", etiqueta: "PZBP - VCON (EMB-DEPORTIVAS)" },
  { id: 545, zona: "PZBP", nombre: "VICT", etiqueta: "PZBP - VICT" },
  { id: 430, zona: "PZBU", nombre: "CLON", etiqueta: "PZBU - CLON" },
  { id: 986, zona: "PZBU", nombre: "CLON (EMB-DEPORTIVAS)", etiqueta: "PZBU - CLON (EMB-DEPORTIVAS)" },
  { id: 472, zona: "PZBU", nombre: "CONC", etiqueta: "PZBU - CONC" },
  { id: 646, zona: "PZBU", nombre: "CONC(EMB-DEPORTIVAS)", etiqueta: "PZBU - CONC(EMB-DEPORTIVAS)" },
  { id: 431, zona: "PZBU", nombre: "CURU", etiqueta: "PZBU - CURU" },
  { id: 623, zona: "PZBU", nombre: "CURU (EMB-DEPORTIVAS)", etiqueta: "PZBU - CURU (EMB-DEPORTIVAS)" },
  { id: 407, zona: "PZBU", nombre: "FEDE", etiqueta: "PZBU - FEDE" },
  { id: 425, zona: "PZBU", nombre: "GYCH", etiqueta: "PZBU - GYCH" },
  { id: 622, zona: "PZBU", nombre: "GYCH (EMB-DEPORTIVAS)", etiqueta: "PZBU - GYCH (EMB-DEPORTIVAS)" },
  { id: 643, zona: "PZBU", nombre: "GYCH (JUR. GUALEGUAY)", etiqueta: "PZBU - GYCH (JUR. GUALEGUAY)" },
  { id: 412, zona: "PZBU", nombre: "PRTO", etiqueta: "PZBU - PRTO" },
  { id: 427, zona: "PZBU", nombre: "SLGR", etiqueta: "PZBU - SLGR" },
  { id: 543, zona: "PZDE", nombre: "BARA", etiqueta: "PZDE - BARA" },
  { id: 611, zona: "PZDE", nombre: "BARA (EMB-DEPORTIVAS)", etiqueta: "PZDE - BARA (EMB-DEPORTIVAS)" },
  { id: 462, zona: "PZDE", nombre: "CAMP", etiqueta: "PZDE - CAMP" },
  { id: 610, zona: "PZDE", nombre: "CAMP (EMB-DEPORTIVAS)", etiqueta: "PZDE - CAMP (EMB-DEPORTIVAS)" },
  { id: 547, zona: "PZDE", nombre: "DLUJ", etiqueta: "PZDE - DLUJ" },
  { id: 1047, zona: "PZDE", nombre: "DLUJ (EMB-DEPORTIVAS)", etiqueta: "PZDE - DLUJ (EMB-DEPORTIVAS)" },
  { id: 447, zona: "PZDE", nombre: "ESCO", etiqueta: "PZDE - ESCO" },
  { id: 609, zona: "PZDE", nombre: "ESCO (EMB-DEPORTIVAS)", etiqueta: "PZDE - ESCO (EMB-DEPORTIVAS)" },
  { id: 684, zona: "PZDE", nombre: "IBIC", etiqueta: "PZDE - IBIC" },
  { id: 544, zona: "PZDE", nombre: "MGAR", etiqueta: "PZDE - MGAR" },
  { id: 478, zona: "PZDE", nombre: "OLIV", etiqueta: "PZDE - OLIV" },
  { id: 607, zona: "PZDE", nombre: "OLIV (EMB-DEPORTIVAS)", etiqueta: "PZDE - OLIV (EMB-DEPORTIVAS)" },
  { id: 483, zona: "PZDE", nombre: "SFER", etiqueta: "PZDE - SFER" },
  { id: 606, zona: "PZDE", nombre: "SFER (EMB-DEPORTIVAS)", etiqueta: "PZDE - SFER (EMB-DEPORTIVAS)" },
  { id: 546, zona: "PZDE", nombre: "SISI", etiqueta: "PZDE - SISI" },
  { id: 421, zona: "PZDE", nombre: "SPED", etiqueta: "PZDE - SPED" },
  { id: 613, zona: "PZDE", nombre: "SPED (EMB-DEPORTIVAS)", etiqueta: "PZDE - SPED (EMB-DEPORTIVAS)" },
  { id: 484, zona: "PZDE", nombre: "TIGR", etiqueta: "PZDE - TIGR" },
  { id: 608, zona: "PZDE", nombre: "TIGR (EMB-DEPORTIVAS)", etiqueta: "PZDE - TIGR (EMB-DEPORTIVAS)" },
  { id: 443, zona: "PZDE", nombre: "ZARA (CANAL DE LA SERNA/MINI)", etiqueta: "PZDE - ZARA (CANAL DE LA SERNA/MINI)" },
  { id: 612, zona: "PZDE", nombre: "ZARA (EMB-DEPORTIVAS)", etiqueta: "PZDE - ZARA (EMB-DEPORTIVAS)" },
  { id: 476, zona: "PZDE", nombre: "ZARA (PARANA BRAVO)", etiqueta: "PZDE - ZARA (PARANA BRAVO)" },
  { id: 475, zona: "PZDE", nombre: "ZARA (PARANA DE LAS PALMAS)", etiqueta: "PZDE - ZARA (PARANA DE LAS PALMAS)" },
  { id: 411, zona: "PZDE", nombre: "ZARA (PARANA GUAZU)", etiqueta: "PZDE - ZARA (PARANA GUAZU)" },
  { id: 465, zona: "PZLC", nombre: "CHUE", etiqueta: "PZLC - CHUE" },
  { id: 459, zona: "PZLC", nombre: "SCBA", etiqueta: "PZLC - SCBA" },
  { id: 480, zona: "PZLC", nombre: "SMAN", etiqueta: "PZLC - SMAN" },
  { id: 482, zona: "PZLC", nombre: "VIAN", etiqueta: "PZLC - VIAN" },
  { id: 452, zona: "PZMN", nombre: "BBLA", etiqueta: "PZMN - BBLA" },
  { id: 706, zona: "PZMN", nombre: "BBLA (Embarcaciones Deportivas)", etiqueta: "PZMN - BBLA (Embarcaciones Deportivas)" },
  { id: 451, zona: "PZMN", nombre: "MADR", etiqueta: "PZMN - MADR" },
  { id: 745, zona: "PZMN", nombre: "MADR (Embarcaciones Deportivas)", etiqueta: "PZMN - MADR (Embarcaciones Deportivas)" },
  { id: 429, zona: "PZMN", nombre: "MPLA", etiqueta: "PZMN - MPLA" },
  { id: 705, zona: "PZMN", nombre: "MPLA (Embarcaciones Deportivas)", etiqueta: "PZMN - MPLA (Embarcaciones Deportivas)" },
  { id: 432, zona: "PZMN", nombre: "PCOL", etiqueta: "PZMN - PCOL" },
  { id: 428, zona: "PZMN", nombre: "PNES", etiqueta: "PZMN - PNES" },
  { id: 885, zona: "PZMN", nombre: "PNES (Embarcaciones Deportivas)", etiqueta: "PZMN - PNES (Embarcaciones Deportivas)" },
  { id: 450, zona: "PZMN", nombre: "QUEQ", etiqueta: "PZMN - QUEQ" },
  { id: 765, zona: "PZMN", nombre: "QUEQ (EMB-DEPORTIVAS)", etiqueta: "PZMN - QUEQ (EMB-DEPORTIVAS)" },
  { id: 461, zona: "PZMN", nombre: "RAWS", etiqueta: "PZMN - RAWS" },
  { id: 906, zona: "PZMN", nombre: "RAWS (EMB-DEPORTIVAS)", etiqueta: "PZMN - RAWS (EMB-DEPORTIVAS)" },
  { id: 434, zona: "PZMN", nombre: "SANT", etiqueta: "PZMN - SANT" },
  { id: 825, zona: "PZMN", nombre: "SANT (EMB-DEPORTIVAS)", etiqueta: "PZMN - SANT (EMB-DEPORTIVAS)" },
  { id: 683, zona: "PZMS", nombre: "CAVI", etiqueta: "PZMS - CAVI" },
  { id: 985, zona: "PZMS", nombre: "CAVI (EMB-DEPORTIVAS)", etiqueta: "PZMS - CAVI (EMB-DEPORTIVAS)" },
  { id: 424, zona: "PZMS", nombre: "CRIV", etiqueta: "PZMS - CRIV" },
  { id: 708, zona: "PZMS", nombre: "CRIV (Embarcaciones Deportivas)", etiqueta: "PZMS - CRIV (Embarcaciones Deportivas)" },
  { id: 435, zona: "PZMS", nombre: "DESE", etiqueta: "PZMS - DESE" },
  { id: 845, zona: "PZMS", nombre: "DESE (EMB-DEPORTIVAS)", etiqueta: "PZMS - DESE (EMB-DEPORTIVAS)" },
  { id: 460, zona: "PZMS", nombre: "LARG", etiqueta: "PZMS - LARG" },
  { id: 453, zona: "PZMS", nombre: "OLVA", etiqueta: "PZMS - OLVA" },
  { id: 865, zona: "PZMS", nombre: "OLVA (Embarcaciones Deportivas)", etiqueta: "PZMS - OLVA (Embarcaciones Deportivas)" },
  { id: 410, zona: "PZMS", nombre: "RGAL", etiqueta: "PZMS - RGAL" },
  { id: 455, zona: "PZMS", nombre: "SCRU", etiqueta: "PZMS - SCRU" },
  { id: 725, zona: "PZMS", nombre: "SCRU (Embarcaciones Deportivas)", etiqueta: "PZMS - SCRU (Embarcaciones Deportivas)" },
  { id: 444, zona: "PZMS", nombre: "SJUL", etiqueta: "PZMS - SJUL" },
  { id: 1005, zona: "PZMS", nombre: "SJUL (EMB-DEPORTIVAS)", etiqueta: "PZMS - SJUL (EMB-DEPORTIVAS)" },
  { id: 413, zona: "PZMS", nombre: "USHU", etiqueta: "PZMS - USHU" },
  { id: 707, zona: "PZMS", nombre: "USHU (Embarcaciones Deportivas)", etiqueta: "PZMS - USHU (Embarcaciones Deportivas)" },
  { id: 415, zona: "PZPP", nombre: "BARR", etiqueta: "PZPP - BARR" },
  { id: 473, zona: "PZPP", nombre: "BERM", etiqueta: "PZPP - BERM" },
  { id: 486, zona: "PZPP", nombre: "BVIS", etiqueta: "PZPP - BVIS" },
  { id: 485, zona: "PZPP", nombre: "COCO", etiqueta: "PZPP - COCO" },
  { id: 805, zona: "PZPP", nombre: "CORR", etiqueta: "PZPP - CORR" },
  { id: 426, zona: "PZPP", nombre: "ESQU", etiqueta: "PZPP - ESQU" },
  { id: 441, zona: "PZPP", nombre: "FORM", etiqueta: "PZPP - FORM" },
  { id: 456, zona: "PZPP", nombre: "GOYA", etiqueta: "PZPP - GOYA" },
  { id: 464, zona: "PZPP", nombre: "ITAT", etiqueta: "PZPP - ITAT" },
  { id: 457, zona: "PZPP", nombre: "PILC", etiqueta: "PZPP - PILC" },
  { id: 417, zona: "PZPP", nombre: "PPAT", etiqueta: "PZPP - PPAT" },
  { id: 481, zona: "PZPP", nombre: "RECO", etiqueta: "PZPP - RECO" },
  { id: 542, zona: "PZRP", nombre: "BOCA", etiqueta: "PZRP - BOCA" },
  { id: 474, zona: "PZRP", nombre: "BSAS (CANAL ACCESO A PUERTO)", etiqueta: "PZRP - BSAS (CANAL ACCESO A PUERTO)" },
  { id: 477, zona: "PZRP", nombre: "BSAS (CANAL EMILIO MITRE)", etiqueta: "PZRP - BSAS (CANAL EMILIO MITRE)" },
  { id: 458, zona: "PZRP", nombre: "BSAS (CANAL MARTIN GARCIA)", etiqueta: "PZRP - BSAS (CANAL MARTIN GARCIA)" },
  { id: 433, zona: "PZRP", nombre: "BSAS (CANAL PUNTA INDIO)", etiqueta: "PZRP - BSAS (CANAL PUNTA INDIO)" },
  { id: 584, zona: "PZRP", nombre: "BSAS (EMB-DEPORTIVAS)", etiqueta: "PZRP - BSAS (EMB-DEPORTIVAS)" },
  { id: 583, zona: "PZRP", nombre: "BSAS (RECALADA)", etiqueta: "PZRP - BSAS (RECALADA)" },
  { id: 521, zona: "PZRP", nombre: "GLAV", etiqueta: "PZRP - GLAV" },
  { id: 965, zona: "PZRP", nombre: "GLAV (EMB-DEPORTIVAS)", etiqueta: "PZRP - GLAV (EMB-DEPORTIVAS)" },
  { id: 409, zona: "PZRP", nombre: "LPLA", etiqueta: "PZRP - LPLA" },
  { id: 605, zona: "PZRP", nombre: "LPLA (EMB-DEPORTIVAS)", etiqueta: "PZRP - LPLA (EMB-DEPORTIVAS)" },
  { id: 663, zona: "PZRP", nombre: "LPLA (PTO BOCA DEL SALADO)", etiqueta: "PZRP - LPLA (PTO BOCA DEL SALADO)" },
  { id: 585, zona: "PZRP", nombre: "QUIL", etiqueta: "PZRP - QUIL" },
];

export default COSTERAS;

export const getNombreCostera = (id) => {
    const costera = COSTERAS.find(c => c.id === id);
    return costera ? costera.etiqueta : "Desconocida";
};